version: '2.1'
services:
  data:
    image: busybox
    volumes:
     - .:/var/www/html/
  web:
    build: Dockerfiles/nodejs/
    environment:
      SLS_DEBUG: "*"
    ports:
      - "4000:4000"
    dns: 8.8.8.8
    volumes_from:
      - data
    networks:
      default:
        aliases:
          - mathjax_page_serverless_web
networks:
  default:
    external:
      name: alexandria_default
